from __future__ import annotations

from dataclasses import dataclass

from src.agents.answer_agent import AnswerDraft
from src.models import RetrievedChunk


@dataclass(frozen=True)
class ValidationReport:
    warnings: list[str]


class ValidationAgent:
    def validate(
        self,
        sources: list[RetrievedChunk],
        draft: AnswerDraft,
        min_relevance_score: float,
    ) -> ValidationReport:
        warnings = list(draft.warnings)

        if not sources:
            _append_unique(warnings, "No source context was available for this answer.")
        else:
            best_score = max(source.relevance_score for source in sources)
            if best_score < min_relevance_score:
                _append_unique(
                    warnings,
                    "The retrieved sources look weak, so treat the answer as tentative.",
                )

        if not draft.answer.strip():
            _append_unique(warnings, "The answer generator returned an empty response.")

        if not draft.used_llm:
            _append_unique(
                warnings,
                "The final answer was not generated by the LLM for this request.",
            )
        elif sources and draft.source_citation_missing:
            _append_unique(
                warnings,
                "The LLM answer did not identify which retrieved sources it used.",
            )

        return ValidationReport(warnings=warnings)


def _append_unique(values: list[str], item: str) -> None:
    if item not in values:
        values.append(item)
